version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.11.1
    networks:
      - backend
    env_file:
      - elasticsearch.env
    healthcheck:
      test: [ "CMD-SHELL", "curl –silent –fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - app.env
    ports:
      - "8080:8080"
networks:
  backend:
    driver: bridge
volumes:
  elasticsearch_data:
    driver: local